
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author t-roy
 */
public class GameScreen extends javax.swing.JFrame {

    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        p1Char = new javax.swing.JTextField();
        p2Char = new javax.swing.JTextField();
        p3Char = new javax.swing.JTextField();
        Player1 = new java.awt.Label();
        Player2 = new java.awt.Label();
        Player3 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        startButton = new javax.swing.JButton();
        newGameBut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        b1x1 = new javax.swing.JButton();
        b1x2 = new javax.swing.JButton();
        b1x3 = new javax.swing.JButton();
        b1x4 = new javax.swing.JButton();
        b1x5 = new javax.swing.JButton();
        b1x6 = new javax.swing.JButton();
        b1x7 = new javax.swing.JButton();
        b1x8 = new javax.swing.JButton();
        b2x1 = new javax.swing.JButton();
        b2x2 = new javax.swing.JButton();
        b2x3 = new javax.swing.JButton();
        b2x4 = new javax.swing.JButton();
        b2x5 = new javax.swing.JButton();
        b2x6 = new javax.swing.JButton();
        b2x7 = new javax.swing.JButton();
        b2x8 = new javax.swing.JButton();
        b3x1 = new javax.swing.JButton();
        b3x2 = new javax.swing.JButton();
        b3x3 = new javax.swing.JButton();
        b3x4 = new javax.swing.JButton();
        b3x5 = new javax.swing.JButton();
        b3x6 = new javax.swing.JButton();
        b3x7 = new javax.swing.JButton();
        b3x8 = new javax.swing.JButton();
        b4x1 = new javax.swing.JButton();
        b4x2 = new javax.swing.JButton();
        b4x3 = new javax.swing.JButton();
        b4x4 = new javax.swing.JButton();
        b4x5 = new javax.swing.JButton();
        b4x6 = new javax.swing.JButton();
        b4x7 = new javax.swing.JButton();
        b4x8 = new javax.swing.JButton();
        b5x1 = new javax.swing.JButton();
        b5x2 = new javax.swing.JButton();
        b5x3 = new javax.swing.JButton();
        b5x4 = new javax.swing.JButton();
        b5x5 = new javax.swing.JButton();
        b5x6 = new javax.swing.JButton();
        b5x7 = new javax.swing.JButton();
        b5x8 = new javax.swing.JButton();
        b6x1 = new javax.swing.JButton();
        b6x2 = new javax.swing.JButton();
        b6x3 = new javax.swing.JButton();
        b6x4 = new javax.swing.JButton();
        b6x5 = new javax.swing.JButton();
        b6x6 = new javax.swing.JButton();
        b6x7 = new javax.swing.JButton();
        b6x8 = new javax.swing.JButton();
        b7x1 = new javax.swing.JButton();
        b7x2 = new javax.swing.JButton();
        b7x3 = new javax.swing.JButton();
        b7x4 = new javax.swing.JButton();
        b7x5 = new javax.swing.JButton();
        b7x6 = new javax.swing.JButton();
        b7x7 = new javax.swing.JButton();
        b7x8 = new javax.swing.JButton();
        b8x1 = new javax.swing.JButton();
        b8x2 = new javax.swing.JButton();
        b8x3 = new javax.swing.JButton();
        b8x4 = new javax.swing.JButton();
        b8x5 = new javax.swing.JButton();
        b8x6 = new javax.swing.JButton();
        b8x7 = new javax.swing.JButton();
        b8x8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(1000, 1200));
        setName("GameScreen"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        p1Char.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 158;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(p1Char, gridBagConstraints);

        p2Char.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 158;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(p2Char, gridBagConstraints);

        p3Char.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 158;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(p3Char, gridBagConstraints);

        Player1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Player1.setEnabled(false);
        Player1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Player1.setText("Player 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(Player1, gridBagConstraints);

        Player2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Player2.setEnabled(false);
        Player2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Player2.setText("Player 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(Player2, gridBagConstraints);

        Player3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Player3.setEnabled(false);
        Player3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Player3.setText("Player 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(Player3, gridBagConstraints);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 0, 32)); // NOI18N
        textArea.setRows(5);
        textArea.setText("Welcome to 4 in a row!\nTake turns selecting boxes until\nsomeone gets 4 in a row.\nEnter the desired character for \neach player, then click 'Start Game'");
        jScrollPane1.setViewportView(textArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 273;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        startButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startButton.setText("Start Game");
        startButton.setOpaque(false);
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(startButton, gridBagConstraints);

        newGameBut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newGameBut.setLabel("New Game");
        newGameBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameButMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(newGameBut, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        b1x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x1.setText(" ");
        b1x1.setEnabled(false);
        b1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x1);

        b1x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x2.setText(" ");
        b1x2.setEnabled(false);
        b1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x2);

        b1x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x3.setText(" ");
        b1x3.setEnabled(false);
        b1x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x3);

        b1x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x4.setText(" ");
        b1x4.setEnabled(false);
        b1x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x4);

        b1x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x5.setText(" ");
        b1x5.setEnabled(false);
        b1x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x5);

        b1x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x6.setText(" ");
        b1x6.setEnabled(false);
        b1x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x6);

        b1x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x7.setText(" ");
        b1x7.setEnabled(false);
        b1x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x7);

        b1x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1x8.setText(" ");
        b1x8.setEnabled(false);
        b1x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1x8);

        b2x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x1.setText(" ");
        b2x1.setEnabled(false);
        b2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x1);

        b2x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x2.setText(" ");
        b2x2.setEnabled(false);
        b2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x2);

        b2x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x3.setText(" ");
        b2x3.setEnabled(false);
        b2x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x3);

        b2x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x4.setText(" ");
        b2x4.setEnabled(false);
        b2x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x4);

        b2x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x5.setText(" ");
        b2x5.setEnabled(false);
        b2x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x5);

        b2x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x6.setText(" ");
        b2x6.setEnabled(false);
        b2x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x6);

        b2x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x7.setText(" ");
        b2x7.setEnabled(false);
        b2x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x7);

        b2x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2x8.setText(" ");
        b2x8.setEnabled(false);
        b2x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b2x8);

        b3x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x1.setText(" ");
        b3x1.setEnabled(false);
        b3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x1);

        b3x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x2.setText(" ");
        b3x2.setEnabled(false);
        b3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x2);

        b3x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x3.setText(" ");
        b3x3.setEnabled(false);
        b3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x3);

        b3x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x4.setText(" ");
        b3x4.setEnabled(false);
        b3x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x4);

        b3x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x5.setText(" ");
        b3x5.setEnabled(false);
        b3x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x5);

        b3x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x6.setText(" ");
        b3x6.setEnabled(false);
        b3x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x6);

        b3x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x7.setText(" ");
        b3x7.setEnabled(false);
        b3x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x7);

        b3x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3x8.setText(" ");
        b3x8.setEnabled(false);
        b3x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b3x8);

        b4x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x1.setText(" ");
        b4x1.setEnabled(false);
        b4x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x1);

        b4x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x2.setText(" ");
        b4x2.setEnabled(false);
        b4x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x2);

        b4x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x3.setText(" ");
        b4x3.setEnabled(false);
        b4x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x3);

        b4x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x4.setText(" ");
        b4x4.setEnabled(false);
        b4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x4);

        b4x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x5.setText(" ");
        b4x5.setEnabled(false);
        b4x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x5);

        b4x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x6.setText(" ");
        b4x6.setEnabled(false);
        b4x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x6);

        b4x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x7.setText(" ");
        b4x7.setEnabled(false);
        b4x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x7);

        b4x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4x8.setText(" ");
        b4x8.setEnabled(false);
        b4x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b4x8);

        b5x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x1.setText(" ");
        b5x1.setEnabled(false);
        b5x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x1);

        b5x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x2.setText(" ");
        b5x2.setEnabled(false);
        b5x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x2);

        b5x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x3.setText(" ");
        b5x3.setEnabled(false);
        b5x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x3);

        b5x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x4.setText(" ");
        b5x4.setEnabled(false);
        b5x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x4);

        b5x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x5.setText(" ");
        b5x5.setEnabled(false);
        b5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x5);

        b5x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x6.setText(" ");
        b5x6.setEnabled(false);
        b5x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x6);

        b5x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x7.setText(" ");
        b5x7.setEnabled(false);
        b5x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x7);

        b5x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5x8.setText(" ");
        b5x8.setEnabled(false);
        b5x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b5x8);

        b6x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x1.setText(" ");
        b6x1.setEnabled(false);
        b6x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x1);

        b6x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x2.setText(" ");
        b6x2.setEnabled(false);
        b6x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x2);

        b6x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x3.setText(" ");
        b6x3.setEnabled(false);
        b6x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x3);

        b6x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x4.setText(" ");
        b6x4.setEnabled(false);
        b6x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x4);

        b6x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x5.setText(" ");
        b6x5.setEnabled(false);
        b6x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x5);

        b6x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x6.setText(" ");
        b6x6.setEnabled(false);
        b6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x6);

        b6x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x7.setText(" ");
        b6x7.setEnabled(false);
        b6x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x7);

        b6x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6x8.setText(" ");
        b6x8.setEnabled(false);
        b6x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b6x8);

        b7x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x1.setText(" ");
        b7x1.setEnabled(false);
        b7x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x1);

        b7x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x2.setText(" ");
        b7x2.setEnabled(false);
        b7x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x2);

        b7x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x3.setText(" ");
        b7x3.setEnabled(false);
        b7x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x3);

        b7x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x4.setText(" ");
        b7x4.setEnabled(false);
        b7x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x4);

        b7x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x5.setText(" ");
        b7x5.setEnabled(false);
        b7x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x5);

        b7x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x6.setText(" ");
        b7x6.setEnabled(false);
        b7x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x6);

        b7x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x7.setText(" ");
        b7x7.setEnabled(false);
        b7x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x7);

        b7x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7x8.setText(" ");
        b7x8.setEnabled(false);
        b7x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b7x8);

        b8x1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x1.setText(" ");
        b8x1.setEnabled(false);
        b8x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x1);

        b8x2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x2.setText(" ");
        b8x2.setEnabled(false);
        b8x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x2);

        b8x3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x3.setText(" ");
        b8x3.setEnabled(false);
        b8x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x3);

        b8x4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x4.setText(" ");
        b8x4.setEnabled(false);
        b8x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x4);

        b8x5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x5.setText(" ");
        b8x5.setEnabled(false);
        b8x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x5);

        b8x6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x6.setText(" ");
        b8x6.setEnabled(false);
        b8x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x6);

        b8x7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x7.setText(" ");
        b8x7.setEnabled(false);
        b8x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x7);

        b8x8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8x8.setText(" ");
        b8x8.setEnabled(false);
        b8x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(b8x8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 4.0;
        gridBagConstraints.weighty = 6.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Start Button event initializes the game when clicked and checks 
     * that each player has a character and none of them are the same.
     */
    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        // ensures each player has a character and none are the same
        if (p1Char.getText().equals("") || p3Char.getText().equals("") 
                || p2Char.getText().equals("")) {
            textArea.setText("Please Enter a character for all players");
        } else if ((p1Char.getText().equals(p2Char.getText()) 
                || (p2Char.getText().equals(p3Char.getText())) 
                || (p3Char.getText().equals(p1Char.getText())))) {
            textArea.setText("Characters cannot be the same.");

        } else {
            //initialize player characters
            p1 = p1Char.getText();
            p2 = p2Char.getText();
            p3 = p3Char.getText();

            p1Char.setEditable(false);
            p3Char.setEditable(false);
            p2Char.setEditable(false);

            pTurn = 1;

            textArea.setText("Player 1's Turn");

            startGame();
           

        }


    }//GEN-LAST:event_startButtonMouseClicked

    
    /*
     * New Game button becomes visible after a game has started. 
     * When pressed, returns the game to the state it was when it opened, 
     * setting the text field to the welcome banner, allowing
     * user to change player characters, showing the start button,
     * and disabling the game board.
    */
    private void newGameButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButMouseClicked
        b1x1.setEnabled(false);
        b1x2.setEnabled(false);
        b1x3.setEnabled(false);
        b1x4.setEnabled(false);
        b1x5.setEnabled(false);
        b1x6.setEnabled(false);
        b1x7.setEnabled(false);
        b1x8.setEnabled(false);
        b2x1.setEnabled(false);
        b2x2.setEnabled(false);
        b2x3.setEnabled(false);
        b2x4.setEnabled(false);
        b2x5.setEnabled(false);
        b2x6.setEnabled(false);
        b2x7.setEnabled(false);
        b2x8.setEnabled(false);
        b3x1.setEnabled(false);
        b3x2.setEnabled(false);
        b3x3.setEnabled(false);
        b3x4.setEnabled(false);
        b3x5.setEnabled(false);
        b3x6.setEnabled(false);
        b3x7.setEnabled(false);
        b3x8.setEnabled(false);
        b4x1.setEnabled(false);
        b4x2.setEnabled(false);
        b4x3.setEnabled(false);
        b4x4.setEnabled(false);
        b4x5.setEnabled(false);
        b4x6.setEnabled(false);
        b4x7.setEnabled(false);
        b4x8.setEnabled(false);
        b5x1.setEnabled(false);
        b5x2.setEnabled(false);
        b5x3.setEnabled(false);
        b5x4.setEnabled(false);
        b5x5.setEnabled(false);
        b5x6.setEnabled(false);
        b5x7.setEnabled(false);
        b5x8.setEnabled(false);
        b6x1.setEnabled(false);
        b6x2.setEnabled(false);
        b6x3.setEnabled(false);
        b6x4.setEnabled(false);
        b6x5.setEnabled(false);
        b6x6.setEnabled(false);
        b6x7.setEnabled(false);
        b6x8.setEnabled(false);
        b7x1.setEnabled(false);
        b7x2.setEnabled(false);
        b7x3.setEnabled(false);
        b7x4.setEnabled(false);
        b7x5.setEnabled(false);
        b7x6.setEnabled(false);
        b7x7.setEnabled(false);
        b7x8.setEnabled(false);
        b8x1.setEnabled(false);
        b8x2.setEnabled(false);
        b8x3.setEnabled(false);
        b8x4.setEnabled(false);
        b8x5.setEnabled(false);
        b8x6.setEnabled(false);
        b8x7.setEnabled(false);
        b8x8.setEnabled(false);

        startButton.setVisible(true);
        p1Char.setText("");
        p2Char.setText("");
        p3Char.setText("");

        b1x1.setText(" ");
        b1x2.setText(" ");
        b1x3.setText(" ");
        b1x4.setText(" ");
        b1x5.setText(" ");
        b1x6.setText(" ");
        b1x7.setText(" ");
        b1x8.setText(" ");
        b2x1.setText(" ");
        b2x2.setText(" ");
        b2x3.setText(" ");
        b2x4.setText(" ");
        b2x5.setText(" ");
        b2x6.setText(" ");
        b2x7.setText(" ");
        b2x8.setText(" ");
        b3x1.setText(" ");
        b3x2.setText(" ");
        b3x3.setText(" ");
        b3x4.setText(" ");
        b3x5.setText(" ");
        b3x6.setText(" ");
        b3x7.setText(" ");
        b3x8.setText(" ");
        b4x1.setText(" ");
        b4x2.setText(" ");
        b4x3.setText(" ");
        b4x4.setText(" ");
        b4x5.setText(" ");
        b4x6.setText(" ");
        b4x7.setText(" ");
        b4x8.setText(" ");
        b5x1.setText(" ");
        b5x2.setText(" ");
        b5x3.setText(" ");
        b5x4.setText(" ");
        b5x5.setText(" ");
        b5x6.setText(" ");
        b5x7.setText(" ");
        b5x8.setText(" ");
        b6x1.setText(" ");
        b6x2.setText(" ");
        b6x3.setText(" ");
        b6x4.setText(" ");
        b6x5.setText(" ");
        b6x6.setText(" ");
        b6x7.setText(" ");
        b6x8.setText(" ");
        b7x1.setText(" ");
        b7x2.setText(" ");
        b7x3.setText(" ");
        b7x4.setText(" ");
        b7x5.setText(" ");
        b7x6.setText(" ");
        b7x7.setText(" ");
        b7x8.setText(" ");
        b8x1.setText(" ");
        b8x2.setText(" ");
        b8x3.setText(" ");
        b8x4.setText(" ");
        b8x5.setText(" ");
        b8x6.setText(" ");
        b8x7.setText(" ");
        b8x8.setText(" ");

        p1Char.setEditable(true);
        p2Char.setEditable(true);
        p3Char.setEditable(true);

        textArea.setText("Welcome to 4 in a row!\n"
                + "Take turns selecting boxes until\n"
                + "someone gets 4 in a row.\n"
                + "Enter the desired character for \n"
                + "each player, then click 'Start Game'");

    }//GEN-LAST:event_newGameButMouseClicked

    /*
     * When a button on the game board is clicked this event function begins.
     * The functions checks for which button was clicked, then checks that
     * there is no text in the button already. If not, the current player's 
     * text is put into the button. 
     * Then the function checks to see if that last move just caused a win with
     * the checkWin function.
     * If it does, it calls the win function. If not, the turn is passed to the
     * next player.
    */
    private void b1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1x1ActionPerformed
               JButton clicked = (JButton) evt.getSource();

        if (clicked.getText().equals(" ")) {

            switch (pTurn) {
                case 1:
                    clicked.setText(p1);
                    break;
                case 2:
                    clicked.setText(p2);
                    break;
                case 3:
                    clicked.setText(p3);
                    break;
                default:
                    clicked.setText("N/A");         // for debugging
                    textArea.setText("Error 1");
                    break;
            }

            if (checkWin()) {
                win();
            } else {
                if (pTurn == 3) {
                    pTurn = 1;
                } else {
                    pTurn++;
                }

                textArea.setText("Player " + pTurn + "'s Turn!");
            }

        }
    }//GEN-LAST:event_b1x1ActionPerformed

    /*
     * Initializes the game board by enabling all the buttons and changing the
     * 'start game' button to the 'new game' button.
    */
    private void startGame() {
        b1x1.setEnabled(true);
        b1x2.setEnabled(true);
        b1x3.setEnabled(true);
        b1x4.setEnabled(true);
        b1x5.setEnabled(true);
        b1x6.setEnabled(true);
        b1x7.setEnabled(true);
        b1x8.setEnabled(true);
        b2x1.setEnabled(true);
        b2x2.setEnabled(true);
        b2x3.setEnabled(true);
        b2x4.setEnabled(true);
        b2x5.setEnabled(true);
        b2x6.setEnabled(true);
        b2x7.setEnabled(true);
        b2x8.setEnabled(true);
        b3x1.setEnabled(true);
        b3x2.setEnabled(true);
        b3x3.setEnabled(true);
        b3x4.setEnabled(true);
        b3x5.setEnabled(true);
        b3x6.setEnabled(true);
        b3x7.setEnabled(true);
        b3x8.setEnabled(true);
        b4x1.setEnabled(true);
        b4x2.setEnabled(true);
        b4x3.setEnabled(true);
        b4x4.setEnabled(true);
        b4x5.setEnabled(true);
        b4x6.setEnabled(true);
        b4x7.setEnabled(true);
        b4x8.setEnabled(true);
        b5x1.setEnabled(true);
        b5x2.setEnabled(true);
        b5x3.setEnabled(true);
        b5x4.setEnabled(true);
        b5x5.setEnabled(true);
        b5x6.setEnabled(true);
        b5x7.setEnabled(true);
        b5x8.setEnabled(true);
        b6x1.setEnabled(true);
        b6x2.setEnabled(true);
        b6x3.setEnabled(true);
        b6x4.setEnabled(true);
        b6x5.setEnabled(true);
        b6x6.setEnabled(true);
        b6x7.setEnabled(true);
        b6x8.setEnabled(true);
        b7x1.setEnabled(true);
        b7x2.setEnabled(true);
        b7x3.setEnabled(true);
        b7x4.setEnabled(true);
        b7x5.setEnabled(true);
        b7x6.setEnabled(true);
        b7x7.setEnabled(true);
        b7x8.setEnabled(true);
        b8x1.setEnabled(true);
        b8x2.setEnabled(true);
        b8x3.setEnabled(true);
        b8x4.setEnabled(true);
        b8x5.setEnabled(true);
        b8x6.setEnabled(true);
        b8x7.setEnabled(true);
        b8x8.setEnabled(true);

        startButton.setVisible(false);

    }
    
    /* 
     * Sets the text field to show which player won the game.
     * Disables all the buttons so players know the game is over.
    */
    private void win() {
        textArea.setText("Player " + pTurn + " Wins!");

        b1x1.setEnabled(false);
        b1x2.setEnabled(false);
        b1x3.setEnabled(false);
        b1x4.setEnabled(false);
        b1x5.setEnabled(false);
        b1x6.setEnabled(false);
        b1x7.setEnabled(false);
        b1x8.setEnabled(false);
        b2x1.setEnabled(false);
        b2x2.setEnabled(false);
        b2x3.setEnabled(false);
        b2x4.setEnabled(false);
        b2x5.setEnabled(false);
        b2x6.setEnabled(false);
        b2x7.setEnabled(false);
        b2x8.setEnabled(false);
        b3x1.setEnabled(false);
        b3x2.setEnabled(false);
        b3x3.setEnabled(false);
        b3x4.setEnabled(false);
        b3x5.setEnabled(false);
        b3x6.setEnabled(false);
        b3x7.setEnabled(false);
        b3x8.setEnabled(false);
        b4x1.setEnabled(false);
        b4x2.setEnabled(false);
        b4x3.setEnabled(false);
        b4x4.setEnabled(false);
        b4x5.setEnabled(false);
        b4x6.setEnabled(false);
        b4x7.setEnabled(false);
        b4x8.setEnabled(false);
        b5x1.setEnabled(false);
        b5x2.setEnabled(false);
        b5x3.setEnabled(false);
        b5x4.setEnabled(false);
        b5x5.setEnabled(false);
        b5x6.setEnabled(false);
        b5x7.setEnabled(false);
        b5x8.setEnabled(false);
        b6x1.setEnabled(false);
        b6x2.setEnabled(false);
        b6x3.setEnabled(false);
        b6x4.setEnabled(false);
        b6x5.setEnabled(false);
        b6x6.setEnabled(false);
        b6x7.setEnabled(false);
        b6x8.setEnabled(false);
        b7x1.setEnabled(false);
        b7x2.setEnabled(false);
        b7x3.setEnabled(false);
        b7x4.setEnabled(false);
        b7x5.setEnabled(false);
        b7x6.setEnabled(false);
        b7x7.setEnabled(false);
        b7x8.setEnabled(false);
        b8x1.setEnabled(false);
        b8x2.setEnabled(false);
        b8x3.setEnabled(false);
        b8x4.setEnabled(false);
        b8x5.setEnabled(false);
        b8x6.setEnabled(false);
        b8x7.setEnabled(false);
        b8x8.setEnabled(false);

    }

    
    /*
     * Uses checkRows, checkCols, and checkDiag functions to see if 
     * a player has won the game.
     * If so, returns true
    */
    private boolean checkWin() {
        // Temporary string to store the current player character.
        String pChar = new String();

        switch (pTurn) {
            case 1:
                pChar = p1;
                break;
            case 2:
                pChar = p2;
                break;
            case 3:
                pChar = p3;
                break;
            default:
                break;
        }

        return (checkRows(pChar)) || (checkCols(pChar)) || (checkDiag(pChar));

    }

    
    /*
     * First calls the initButtonArr function to fill the button array with
     * the current characters in the game grid. This is called every turn to 
     * fill the array with all the changes every time someone clicks a button.
     * Checks each diagonal of the grid for a win by using loops to create a
     * string for each diagonal line, then checking if that string contains
     * the sequence of 4 player characters.
    */
    private boolean checkDiag(String pChar) {

        initButtonArray();

        String dia1 = new String("");
        String dia2 = new String("");
        String dia3 = new String("");
        String dia4 = new String("");
        String dia5 = new String("");
        String dia6 = new String("");
        String dia7 = new String("");
        String dia8 = new String("");
        String dia9 = new String("");
        String dia10 = new String("");
        String dia11 = new String("");
        String dia12 = new String("");
        String dia13 = new String("");
        String dia14 = new String("");
        String dia15 = new String("");
        String dia16 = new String("");
        String dia17 = new String("");
        String dia18 = new String("");

        
        for (int i = 1; i <= 8; i++) {
            dia1 = dia1.concat(buttonArr[i][i]);
        }
        for (int i = 1; i <= 7; i++) {
            dia2 = dia2.concat(buttonArr[i + 1][i]);
            dia6 = dia6.concat(buttonArr[i][i + 1]);
        }
        for (int i = 1; i <= 6; i++) {
            dia3 = dia3.concat(buttonArr[i + 2][i]);
            dia7 = dia7.concat(buttonArr[i][i + 2]);
        }
        for (int i = 1; i <= 5; i++) {
            dia4 = dia4.concat(buttonArr[i + 3][i]);
            dia8 = dia8.concat(buttonArr[i][i + 3]);
        }
        for (int i = 1; i <= 4; i++) {
            dia5 = dia5.concat(buttonArr[i + 4][i]);
            dia9 = dia9.concat(buttonArr[i][i + 4]);
        }
        for (int i = 8, j = 1; i >= 1 && j <= 8; i--, j++) {
            dia10 = dia10.concat(buttonArr[j][i]);
        }
        for (int i = 7, j = 1; i >= 1 && j <= 7; i--, j++) {
            dia11 = dia11.concat(buttonArr[j][i]);
            dia15 = dia15.concat(buttonArr[j + 1][i + 1]);
        }
        for (int i = 6, j = 1; i >= 1 && j <= 6; i--, j++) {
            dia12 = dia12.concat(buttonArr[j][i]);
            dia16 = dia16.concat(buttonArr[j + 2][i + 2]);
        }
        for (int i = 5, j = 1; i >= 1 && j <= 5; i--, j++) {
            dia13 = dia13.concat(buttonArr[j][i]);
            dia17 = dia17.concat(buttonArr[j + 3][i + 3]);
        }
        for (int i = 4, j = 1; i >= 1 && j <= 4; i--, j++) {
            dia14 = dia14.concat(buttonArr[j][i]);
            dia18 = dia18.concat(buttonArr[j + 4][i + 4]);
        }

        return (dia1.contains(pChar + pChar + pChar + pChar))
                || (dia2.contains(pChar + pChar + pChar + pChar))
                || (dia3.contains(pChar + pChar + pChar + pChar))
                || (dia4.contains(pChar + pChar + pChar + pChar))
                || (dia5.contains(pChar + pChar + pChar + pChar))
                || (dia6.contains(pChar + pChar + pChar + pChar))
                || (dia7.contains(pChar + pChar + pChar + pChar))
                || (dia8.contains(pChar + pChar + pChar + pChar))
                || (dia9.contains(pChar + pChar + pChar + pChar))
                || (dia10.contains(pChar + pChar + pChar + pChar))
                || (dia11.contains(pChar + pChar + pChar + pChar))
                || (dia12.contains(pChar + pChar + pChar + pChar))
                || (dia13.contains(pChar + pChar + pChar + pChar))
                || (dia14.contains(pChar + pChar + pChar + pChar))
                || (dia15.contains(pChar + pChar + pChar + pChar))
                || (dia16.contains(pChar + pChar + pChar + pChar))
                || (dia17.contains(pChar + pChar + pChar + pChar))
                || (dia18.contains(pChar + pChar + pChar + pChar));
    }

    /*
     * First calls the initButtonArr function to fill the button array with
     * the current characters in the game grid. This is called every turn to 
     * fill the array with all the changes every time someone clicks a button.
     * Checks each column of the grid for a win by using a loop to create a
     * string for each vertical line, then checking if that string contains
     * the sequence of 4 player characters.
    */
    private boolean checkCols(String pChar) {

        initButtonArray();

        String col1 = new String("");
        String col2 = new String("");
        String col3 = new String("");
        String col4 = new String("");
        String col5 = new String("");
        String col6 = new String("");
        String col7 = new String("");
        String col8 = new String("");

        for (int i = 1; i <= 8; i++) {
            col1 = col1.concat(buttonArr[i][1]);
            col2 = col2.concat(buttonArr[i][2]);
            col3 = col3.concat(buttonArr[i][3]);
            col4 = col4.concat(buttonArr[i][4]);
            col5 = col5.concat(buttonArr[i][5]);
            col6 = col6.concat(buttonArr[i][6]);
            col7 = col7.concat(buttonArr[i][7]);
            col8 = col8.concat(buttonArr[i][8]);
        }

        return (col1.contains(pChar + pChar + pChar + pChar))
                || (col2.contains(pChar + pChar + pChar + pChar))
                || (col3.contains(pChar + pChar + pChar + pChar))
                || (col4.contains(pChar + pChar + pChar + pChar))
                || (col5.contains(pChar + pChar + pChar + pChar))
                || (col6.contains(pChar + pChar + pChar + pChar))
                || (col7.contains(pChar + pChar + pChar + pChar))
                || (col8.contains(pChar + pChar + pChar + pChar));

    }

     /*
     * First calls the initButtonArr function to fill the button array with
     * the current characters in the game grid. This is called every turn to 
     * fill the array with all the changes every time someone clicks a button.
     * Checks each row of the grid for a win by using a loop to create a
     * string for each horizontal line, then checking if that string contains
     * the sequence of 4 player characters.
    */
    private boolean checkRows(String pChar) {
        initButtonArray();

        String row1 = new String("");
        String row2 = new String("");
        String row3 = new String("");
        String row4 = new String("");
        String row5 = new String("");
        String row6 = new String("");
        String row7 = new String("");
        String row8 = new String("");

        for (int i = 1; i <= 8; i++) {
            row1 = row1.concat(buttonArr[1][i]);
            row2 = row2.concat(buttonArr[2][i]);
            row3 = row3.concat(buttonArr[3][i]);
            row4 = row4.concat(buttonArr[4][i]);
            row5 = row5.concat(buttonArr[5][i]);
            row6 = row6.concat(buttonArr[6][i]);
            row7 = row7.concat(buttonArr[7][i]);
            row8 = row8.concat(buttonArr[8][i]);

        }

        return (row1.contains(pChar + pChar + pChar + pChar))
                || (row2.contains(pChar + pChar + pChar + pChar))
                || (row3.contains(pChar + pChar + pChar + pChar))
                || (row4.contains(pChar + pChar + pChar + pChar))
                || (row5.contains(pChar + pChar + pChar + pChar))
                || (row6.contains(pChar + pChar + pChar + pChar))
                || (row7.contains(pChar + pChar + pChar + pChar))
                || (row8.contains(pChar + pChar + pChar + pChar));

    }

    /*
     * Fills the two-dimensional button array with each the contents of each
     * button. This makes the button text easier to access when searching for
     * a winner, rather than calling b1x1.getText(), b1x2.getText(), 
     * b1x3.getText()... etc. every time. 
     * Since our buttons are named by their spot on the grid starting at
     * "1x1", to make them match up nicely we start initializing them at
     * buttonArr[1][1]. So that b1x1 will be at buttonArr[1][1] instead of 
     * at buttonArr[0][0]. 
    */
    private void initButtonArray() {
        /* This initializes row 0 and column 0 to the empty string. 
           This ensures that the 0 row and column will have no affect on the
           final string for each row and column.  
        */
        for (int i = 0; i <= 8; i++) {
            buttonArr[i][0] = "";
            buttonArr[0][i] = "";
        }

        buttonArr[1][1] = b1x1.getText();
        buttonArr[1][2] = b1x2.getText();
        buttonArr[1][3] = b1x3.getText();
        buttonArr[1][4] = b1x4.getText();
        buttonArr[1][5] = b1x5.getText();
        buttonArr[1][6] = b1x6.getText();
        buttonArr[1][7] = b1x7.getText();
        buttonArr[1][8] = b1x8.getText();
        buttonArr[2][1] = b2x1.getText();
        buttonArr[2][2] = b2x2.getText();
        buttonArr[2][3] = b2x3.getText();
        buttonArr[2][4] = b2x4.getText();
        buttonArr[2][5] = b2x5.getText();
        buttonArr[2][6] = b2x6.getText();
        buttonArr[2][7] = b2x7.getText();
        buttonArr[2][8] = b2x8.getText();
        buttonArr[3][1] = b3x1.getText();
        buttonArr[3][2] = b3x2.getText();
        buttonArr[3][3] = b3x3.getText();
        buttonArr[3][4] = b3x4.getText();
        buttonArr[3][5] = b3x5.getText();
        buttonArr[3][6] = b3x6.getText();
        buttonArr[3][7] = b3x7.getText();
        buttonArr[3][8] = b3x8.getText();
        buttonArr[4][1] = b4x1.getText();
        buttonArr[4][2] = b4x2.getText();
        buttonArr[4][3] = b4x3.getText();
        buttonArr[4][4] = b4x4.getText();
        buttonArr[4][5] = b4x5.getText();
        buttonArr[4][6] = b4x6.getText();
        buttonArr[4][7] = b4x7.getText();
        buttonArr[4][8] = b4x8.getText();
        buttonArr[5][1] = b5x1.getText();
        buttonArr[5][2] = b5x2.getText();
        buttonArr[5][3] = b5x3.getText();
        buttonArr[5][4] = b5x4.getText();
        buttonArr[5][5] = b5x5.getText();
        buttonArr[5][6] = b5x6.getText();
        buttonArr[5][7] = b5x7.getText();
        buttonArr[5][8] = b5x8.getText();
        buttonArr[6][1] = b6x1.getText();
        buttonArr[6][2] = b6x2.getText();
        buttonArr[6][3] = b6x3.getText();
        buttonArr[6][4] = b6x4.getText();
        buttonArr[6][5] = b6x5.getText();
        buttonArr[6][6] = b6x6.getText();
        buttonArr[6][7] = b6x7.getText();
        buttonArr[6][8] = b6x8.getText();
        buttonArr[7][1] = b7x1.getText();
        buttonArr[7][2] = b7x2.getText();
        buttonArr[7][3] = b7x3.getText();
        buttonArr[7][4] = b7x4.getText();
        buttonArr[7][5] = b7x5.getText();
        buttonArr[7][6] = b7x6.getText();
        buttonArr[7][7] = b7x7.getText();
        buttonArr[7][8] = b7x8.getText();
        buttonArr[8][1] = b8x1.getText();
        buttonArr[8][2] = b8x2.getText();
        buttonArr[8][3] = b8x3.getText();
        buttonArr[8][4] = b8x4.getText();
        buttonArr[8][5] = b8x5.getText();
        buttonArr[8][6] = b8x6.getText();
        buttonArr[8][7] = b8x7.getText();
        buttonArr[8][8] = b8x8.getText();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    //strings for each player character
    String p1; 
    String p2;
    String p3;
    int pTurn; // determines who's turn it is.
    
    /* Button array has a size of 9 so that the places go up to 8 and can match
        up with the number of each button. Just makes it easier to think about.
    */
    String buttonArr[][] = new String[9][9]; 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Player1;
    private java.awt.Label Player2;
    private java.awt.Label Player3;
    private javax.swing.JButton b1x1;
    private javax.swing.JButton b1x2;
    private javax.swing.JButton b1x3;
    private javax.swing.JButton b1x4;
    private javax.swing.JButton b1x5;
    private javax.swing.JButton b1x6;
    private javax.swing.JButton b1x7;
    private javax.swing.JButton b1x8;
    private javax.swing.JButton b2x1;
    private javax.swing.JButton b2x2;
    private javax.swing.JButton b2x3;
    private javax.swing.JButton b2x4;
    private javax.swing.JButton b2x5;
    private javax.swing.JButton b2x6;
    private javax.swing.JButton b2x7;
    private javax.swing.JButton b2x8;
    private javax.swing.JButton b3x1;
    private javax.swing.JButton b3x2;
    private javax.swing.JButton b3x3;
    private javax.swing.JButton b3x4;
    private javax.swing.JButton b3x5;
    private javax.swing.JButton b3x6;
    private javax.swing.JButton b3x7;
    private javax.swing.JButton b3x8;
    private javax.swing.JButton b4x1;
    private javax.swing.JButton b4x2;
    private javax.swing.JButton b4x3;
    private javax.swing.JButton b4x4;
    private javax.swing.JButton b4x5;
    private javax.swing.JButton b4x6;
    private javax.swing.JButton b4x7;
    private javax.swing.JButton b4x8;
    private javax.swing.JButton b5x1;
    private javax.swing.JButton b5x2;
    private javax.swing.JButton b5x3;
    private javax.swing.JButton b5x4;
    private javax.swing.JButton b5x5;
    private javax.swing.JButton b5x6;
    private javax.swing.JButton b5x7;
    private javax.swing.JButton b5x8;
    private javax.swing.JButton b6x1;
    private javax.swing.JButton b6x2;
    private javax.swing.JButton b6x3;
    private javax.swing.JButton b6x4;
    private javax.swing.JButton b6x5;
    private javax.swing.JButton b6x6;
    private javax.swing.JButton b6x7;
    private javax.swing.JButton b6x8;
    private javax.swing.JButton b7x1;
    private javax.swing.JButton b7x2;
    private javax.swing.JButton b7x3;
    private javax.swing.JButton b7x4;
    private javax.swing.JButton b7x5;
    private javax.swing.JButton b7x6;
    private javax.swing.JButton b7x7;
    private javax.swing.JButton b7x8;
    private javax.swing.JButton b8x1;
    private javax.swing.JButton b8x2;
    private javax.swing.JButton b8x3;
    private javax.swing.JButton b8x4;
    private javax.swing.JButton b8x5;
    private javax.swing.JButton b8x6;
    private javax.swing.JButton b8x7;
    private javax.swing.JButton b8x8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newGameBut;
    private javax.swing.JTextField p1Char;
    private javax.swing.JTextField p2Char;
    private javax.swing.JTextField p3Char;
    private javax.swing.JButton startButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
